# https://docs.github.com/en/actions/creating-actions/about-custom-actions
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Get Git Version
description: Compute the version based on git using GitVersion Tool

outputs:
  version:
    description: git version
    value: ${{ steps.git-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install And Run GitVersion Tool
      shell: bash
      run: dotnet tool install -g gitversion.tool --version 5.* && dotnet-gitversion /output buildserver
    - name: Set Version
      shell: bash
      run: echo "version=${{ env.GitVersion_MajorMinorPatch }}${{ env.GitVersion_PreReleaseLabel && format('-{0}.{1}', env.GitVersion_PreReleaseLabel, github.run_number) || '' }}" >> $GITHUB_OUTPUT
      id: git-version
